### ISSUE TITLE
[Discussion] Google increase Meta-Description to 320 length

### ISSUE THREAD

**Issue by akroii** [derhaeuptling/contao-seo-serp-preview#10]
Since december google accept 320 instead of 170 chars.
[https://moz.com/blog/googles-longer-snippets](https://moz.com/blog/googles-longer-snippets)
In my opinion, 320 chars will not improve UX in google SERPS, because of its length.

Maybe as option in backend?

**Comment by Metis77** [comment]
The new limit has already been introduced in 280efa8.
Less than 320 chars can be typed any time. Therefore I think an option for a lower limit is not needed.
