### ISSUE TITLE
SERP preview shows basic entities

### ISSUE THREAD

**Issue by fritzmg** [derhaeuptling/contao-seo-serp-preview#12]
If you use `[-]` for example in your news headline or page title, the SERP preview will show these characters.

The preview should simply remove those tagged entities - or use
```php
\Contao\StringUtil::restoreBasicEntities(…)
```

**Comment by qzminski** [comment]
Hey @fritzmg can you try 50665a6 please?

**Comment by fritzmg** [comment]
Hm, I cannot install without defining the repo. There seems to be an issue with your packagist integration: https://packagist.org/packages/derhaeuptling/contao-seo-serp-preview#dev-master

**Comment by qzminski** [comment]
Huh? What's the error that you get?

**Comment by fritzmg** [comment]
Only you can see the error - what I mean is, that packagist ist not updated: https://packagist.org/packages/derhaeuptling/contao-seo-serp-preview#dev-master

dev-master is still at f82ff78054597c252f86c0ba789d365c174a1842

**Comment by Metis77** [comment]
@fritzmg packagist is now in sync again with github.

**Comment by qzminski** [comment]
@fritzmg any news on this? 😇

**Comment by fritzmg** [comment]
It works - but not in the live preview i.e. when you type "Rhetorik[-]training" it will still show "Rhetorik[-]training" in the live SERP preview. When you save, the "[-]" will not be displayed.

**Comment by qzminski** [comment]
I think 8cfd0cc will do now. Seems to work fine for me with the live preview but I'd appreciate if you can test it, too.

**Comment by fritzmg** [comment]
Yep, works 👍

**Comment by qzminski** [comment]
Thanks for the feedback, just tagged 3.0.5.

**Comment by Metis77** [comment]
@fritzmg @qzminski thank you both!
