### ISSUE TITLE
Verwenden des mit Contao 4.7 neu eingeführten Feldes "Meta-Beschreibung" bei Events

### ISSUE THREAD

**Issue by joehi** [derhaeuptling/contao-seo-serp-preview#13]
Seit Contao 4.7 gibt es bei Events das neue, optionale Feld "Meta-Beschreibung", das den Teasertext überschreibt. In der SERP-Vorschau wird dieses neue Feld bisher ignoriert und immer der Teasertext verwendet.

**Comment by Metis77** [comment]
deprecated in favour of the Contao 4.9 SERP Feature
