### ISSUE TITLE
Zeichenanzahl in der SERP Vorschau entspricht nicht der Google Zeichenanzahl

### ISSUE THREAD

**Issue by cmichael-de** [derhaeuptling/contao-seo-serp-preview#14]
Das Modul schlägt 320 Zeichen vor. 

In der Googleanzeige werden aber nur 120 Zeichen angezeigt, die dann abgeschnitten werden.

Die Empfehlung ist maximal 160 zu setzen.

**Comment by Metis77** [comment]
Danke für den Input.
Google ändert hier immer mal wieder was und wir müssen dann überlegen, wie damit umzugehen ist.

Früher lag das maximum mal bei 172 Zeichen.
2018 wurde das geändert und ein Maximum von 320 Zeichen eingeführt.
Inzwischen, könnte es sogar so sein, dass es kein Maximum mehr gibt.

Entscheident ist jedoch zu verstehen, dass die Länge der Anzeige von der Suche selber und von der Displaygröße abhängt.
Auf Handys wird zB in der Regel eine längere Version angezeigt.

Mehr zu dem Thema hier:
https://seopressor.com/blog/google-title-meta-descriptions-length/
oder hier
https://www.portent.com/blog/seo/new-character-length-google-serp-snippets-meta-descriptions.htm

**Comment by cmichael-de** [comment]
Eine kleine schnelle Idee: Vielleicht kann man ein Feld in den Einstellungen implementieren, mit dem der Admin den Default von 320 überschreiben kann. Dann können die Admins selber auf Google-Änderungen reagieren.

**Comment by Metis77** [comment]
Meiner Erfahrung nach, würde das eher zu Falscheinschätzungen führen.
Außerdem würde dann im Falln von neuen Änderungen durch Google dieser keiner mehr per Update des Plugins bekommen.

**Comment by cmichael-de** [comment]
Ich denke, wenn dort 320 steht und das bei Google dann aber abgeschnitten wird, dass Plugin aber nicht die (abgeschnitte) Vorschau zeigt, dann gibt's da auch schnell eine Falscheinschätzungen.

Aber dein Hinweis mit den Updates sehe ich sofort ein. Ich denke, da wäre meine Idee kontraprodukttiv.

Um das mit der Falscheinschätzung zu verbessern, könnte man einen Hinweis anzeigen, dass die Ansicht bei Google abweichen kann. Oder mit css eclipse entsprechend die Vorschau abschneiden und dass dann noch responsive ... das klingt nach etwas mehr Arbeit :-) ... aber ein Hinweis verbessert das schöne Modul und macht es noch besser.

**Comment by Metis77** [comment]
Die Anzeige entspricht derzeit dem, was Google auch zB auf Mobilgeräten ausgibt.
Wenn wir das nun verkürzen, führt das genauso in die Irre, nur andersrum.

Und wir würden ein Limit einführen, welches nicht mehr dem Google Limit entspricht – wir würde also noch mehr falsch machen.

Der Contao Hinweis unter der Seitenbeschreibung weist aber genau auf diese Problematik hin:
"Suchmaschinen indizieren normalerweise zwischen 150 und 300 Zeichen."

Evtl. sollten wir den Text "SERP Vorschau" in "mögliche SERP Vorschau" ändern :)

**Comment by cmichael-de** [comment]
Jupp und ...

Mögl. SERP Vorschau (Beschreibung kann in Google abgeschnitten werden)

https://nimb.ws/UDrOFs

**Comment by Metis77** [comment]
added in 8160adb593571057149b52167b65b27dad36a415
