### ISSUE TITLE
Pb when trying to install under Contao 3.5.16

### ISSUE THREAD

**Issue by JLBA** [derhaeuptling/contao-seo-serp-preview#2]
Hi,
I'm trying to install contao-seo-serp-preview using Composer in Contao 3.5.16 . But when the scripts after download seem to be finished, I got a blank page with the text below. And nothing else. The same page in FE and BE. I must suppress the files directly by ftp for the site to work again.

Thanks for your help. 

```
Array
(
    [seo_serp_preview] => Array
        (
            [0] => core
            [1] => _autoload
            [2] => calendar
            [3] => news
        )

)
```

![capture 2016-09-29 a 18 49 13](https://cloud.githubusercontent.com/assets/2730432/18963738/75db85bc-8676-11e6-8f3b-1c9c0ff2388a.png)

**Comment by qzminski** [comment]
Fixed in 36e4458.

**Comment by JLBA** [comment]
Thanks for the quick fix. But know, I got only a blank page (FE and BE) with: "Fatal error: Class 'NamespaceClassLoader' not found in /Users/pro/CLIENTS/EEFIC/www/sitev3-B/system/modules/seo_serp_preview/config/autoload.php on line 17"  

JL Test
jltest@free.fr

**Comment by Metis77** [comment]
try to delete & reinstall.
Dependency NamespaceClassLoader should automatically be installed too.

**Comment by JLBA** [comment]
Done it 3 times. Don’t work.

**Comment by qzminski** [comment]
Sorry, can you also try c196a6b?

**Comment by JLBA** [comment]
I can't do that today but on monday.
Thx

## 

JL Barts-Andreetto

**Comment by qzminski** [comment]
I have tested it locally, now it should work. @Metis77 can you release 2.2.2?

**Comment by JLBA** [comment]
Finally I took 5 minutes to test. 

OK/. Whith 2.2.2 the installation goes well. But now, when clicking to SEO SERP or Site structure, I get : 

"Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /Users/pro/CLIENTS/EEFIC/www/sitev3-B/composer/vendor/derhaeuptling/contao-seo-serp-preview/src/Derhaeuptling/SeoSerpPreview/TestsHandler/AbstractHandler.php on line 182"

**Comment by qzminski** [comment]
Good catch, please try 2.2.3 😄

**Comment by JLBA** [comment]
ok. I seems to work.
 Thanks.
