### ISSUE TITLE
Margin in Contao 4 BE

### ISSUE THREAD

**Issue by bastibuck** [derhaeuptling/contao-seo-serp-preview#4]
Hey,

thanks for this extension first of all. 
Just stumbled across it for the first time and see the use of it. 

Installed in up to date contao 4 standard edition I came across a small visual bug:

![seo](https://cloud.githubusercontent.com/assets/6306291/22862450/1ea845fe-f12f-11e6-870c-5f09197394d2.png)

Could you add the CSS class "widget" to the BE seo serp preview to match standard BE classes and have proper margin. 

`<div class="tl_formbody_edit seo-serp-module widget">`

Thank you

**Comment by qzminski** [comment]
Fixed in 81dcc40, thanks!

**Comment by bastibuck** [comment]
Would you make it a 3.0.1 tag, too? ;-) 
Thanks for the quick fix!

Cheers

**Comment by qzminski** [comment]
Ah sorry, yes, done.
