### ISSUE TITLE
Enable "ignore seo serp" for regular pages

### ISSUE THREAD

**Issue by bastibuck** [derhaeuptling/contao-seo-serp-preview#5]
Hey again,

quick question: Why is ignoring a page only usable for root pages? 

Would like to also ignore regular pages since I use them to edit elements I include in other pages (e.g. contact information). 

Cheers

**Comment by qzminski** [comment]
@Metis77 what do you think?

**Comment by Metis77** [comment]
@bastibuck  I am no sure on this. Why do you think, there should be a "Ignore this page" on every page?

Right now, a page will be ignored, if:
- not visible
- Robots: noindex

**Comment by bastibuck** [comment]
Oh okay, Didn't find the Robots: noindex way. That's enough then. Thanks :-)

**Comment by Metis77** [comment]
@bastibuck I appreciate you feedback.
If you can think of any improvements don´t hold yourself back.

**Comment by bastibuck** [comment]
Just installed yesterday. If I find anything I'll let you guys know!
Thanks for the quick response and fix.
Best
