### ISSUE TITLE
issue with menu in Contao 4.5-beta

### ISSUE THREAD

**Issue by fritzmg** [derhaeuptling/contao-seo-serp-preview#7]
In the current Contao 4.5-beta3, the back end menu item looks like this:

![seo](https://user-images.githubusercontent.com/4970961/33773063-01a174d2-dc37-11e7-8719-93f837251f49.png)

Not sure what changed between Contao 4.4 and 4.5 here.

**Comment by Metis77** [comment]
@qzminski 
what do you think on this?

**Comment by fritzmg** [comment]
The reason for this is that the back end menu has been implemented via a Twig template now. Twig automatically uses output encoding.

v4.4: [src/Resources/contao/templates/backend/be_main.html5](https://github.com/contao/core-bundle/blob/4.4/src/Resources/contao/templates/backend/be_main.html5#L60-L77)
v4.5: [src/Resources/views/Backend/be_menu.html.twig](https://github.com/contao/core-bundle/blob/4.5/src/Resources/views/Backend/be_menu.html.twig)

**Comment by fritzmg** [comment]
May be use a custom insert tag instead in order to inject the HTML.

**Comment by fritzmg** [comment]
Fixed in https://github.com/contao/core-bundle/commit/00f0411f18091c0bd9e6e23684308b7ac6bc79a4
