### ISSUE TITLE
New Preview length in SERP

### ISSUE THREAD

**Issue by Metis77** [derhaeuptling/contao-seo-serp-preview#8]
https://www.inc.com/john-lincoln/googles-new-meta-description-length-what-you-need-to-know.html

consider the length now being 320 signs.

**Comment by fritzmg** [comment]
I could not find any reliable source for it being 320 characters. The statistics from [Rank Ranger](https://www.rankranger.com/google-serp-features) show an increase to almost __230__ characters on average. May be someone just made a typo ;).

This also requires a change within Contao. See https://github.com/contao/core-bundle/pull/1258

**Comment by Metis77** [comment]
According to my own tests and to this article (https://moz.com/blog/how-long-should-your-meta-description-be-2018) the new length might be around 300.

@fritzmg 
What do you think?


About the 230 characters:
some articles are talking about an 230 average ... not maximum.
some articles omit the word "average" and just say 230.

**Comment by fritzmg** [comment]
Imho Contao should trim to the maximum (320) and this extension should test for the observed average (230).

**Comment by qzminski** [comment]
Bumped to 320 characters in 280efa8.

**Comment by fritzmg** [comment]
If the character limit for news and events is not increased in the core-bundle, may be this extension can introduce a hook implementation instead.

**Comment by fritzmg** [comment]
Die automatische Länge für news und events ist nun auch im Contao Core auf 320 angehoben: https://github.com/contao/core-bundle/commit/d868f699e1e5af8aad8e01a79c34bdbc1043fe70
