### ISSUE TITLE
Anzeige aktualisiert sich nicht

### ISSUE THREAD

**Issue by designpilot** [derhaeuptling/contao-seo-serp-preview#9]
Hallo @Metis77
Ich habe die Erweiterung über den Contao Manager installiert nur wenn ich jetzt in der Seitenstruktur eine Seite öffne und dort schauen will wie der Eintrag auf google aussehen könnte wird nichts generiert/angezeigt.

Screenshot der Anzeige im BE (Contao 4.4.9)
https://picload.org/view/dddraawa/screenshot.png.html

Der erste blaue Streifen sagt ja aus das man Daten eingeben soll das man das Preview sieht und die zweite besagt das die entsprechende Seite nicht von den Suchmaschinen indexiert wird (anscheinend soll die robots.txt damit zu tun haben, wobei unter Contao 4.4.9 gibt es in diesem Sinne ja keine robots.txt mehr, ein paar sagen die sei sowieso überflüssig).

Kannst Du da eine Lösung dazu bieten ????
Greets Didier

**Comment by Metis77** [comment]
<img width="1183" alt="bildschirmfoto 2017-12-26 um 21 51 13" src="https://user-images.githubusercontent.com/1408361/34364503-fd6bcfa8-ea86-11e7-90bd-0fdbc9d54f66.png">

Anscheinend hast du den Suchmaschinen das Indexieren per Einstellung (siehe Screenshot) verboten.
In einem solchem Fall, deaktiviert sich SEO SERP automatisch.

Hilft dir das weiter?

**Comment by designpilot** [comment]
Also auf der einen Seite wo ich es getestet habe, dort ist index,follow eingestellt also dürft diese Anzeige so ja nicht erscheinen und alles andere stimmt ja ich hab das auch nach deiner Anleitung gemacht.

Kann es auch sein die Seite im Wartungsmodus ist es auch blockiert wird ????

**Comment by Metis77** [comment]
Ah stimmt, jetzt kann ich das reproduzieren.
Im Wartungsmodus funktioniert das Plugin nicht.

Vielen Dank für den Bug Report.
Wir schauen uns das bei Gelegenheit an.

**Comment by designpilot** [comment]
Ich werde das morgen gleich nochmal testen, kann es auch sein weil es eine Subdomain ist das es nicht funktioniert ??? Weil das ist die Entwicklungsdomain, wenn fertig wird es von dev.meinedomain.tld nach meinedomain.tld umgestellt.

**Comment by Metis77** [comment]
Eben auch nochmals getestet.
Es scheint alles normal zu funktionieren. Auch im Wartungsmodus.

Nichts desto trotz, wenn du den Fehler nochmal hast, und ihn reproduzierbar bekommst, freue ich mich über deinen Bugreport.

Derweil schließe ich den Issue hier.
